networks:
  infra:
    external: true

volumes:
  postgres_data:
  redis_data:

services:
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - infra
    ports:
      - 5432:5432
    restart: always

  redis:
    container_name: redis
    image: redis:7.4
    command: redis-server --requirepass redis
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - redis_data:/var/lib/redis
    networks:
      - infra
    ports:
      - 6379:6379
    restart: always

#  web:
#    image: nginx:alpine
#    restart: always
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    command: [ nginx-debug, '-g', 'daemon off;' ]
#    ports:
#      - 8012:8090
#    networks:
#      - deploy_infra